# Generated by Django 4.2 on 2023-04-16 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateInit', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField()),
                ('boton1', models.IntegerField(default=0)),
                ('boton2', models.IntegerField(default=0)),
                ('timeInit', models.DateTimeField()),
                ('timeFinal', models.DateTimeField()),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.users')),
            ],
        ),
    ]
