# Generated by Django 4.2 on 2023-04-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
